name = "feather_rp2040_bsp"
description = "Board support package for the Adafruit Feather RP2040"
version = "0.7.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
tags = ["embedded", "nostd", "adafruit", "feather", "rp2040", "bsp"]

[[depends-on]]
rp2040_hal = "~0.7.0"

[configuration.values]
rp2040_hal.Flash_Chip = "generic_qspi"
