name = "uart_interrupt"
description = "hello_world_ada_pico"
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["uart_interrupt"]

[[depends-on]]
pico_bsp = "^2"
chests = "~0.1.1"
